name: Sync Docker Images to Aliyun ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
      # 1. 安装必需的skopeo工具（无需Docker）
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      # 2. 登录阿里云ACR（个人版）
      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: crpi-xgj9z1app199hujj.cn-shanghai.personal.cr.aliyuncs.com  # 替换为你的个人ACR地址
          username: ${{ secrets.ALIYUN_USERNAME }}  # 阿里云账号（通常是RAM子账号）
          password: ${{ secrets.ALIYUN_PASSWORD }}  # 阿里云密码或临时令牌

      # 3. 同步镜像（支持单镜像或批量同步）
      - name: Sync Images
        run: |
          # 单镜像同步示例（公开镜像，无需Docker Hub登录）
          skopeo copy \
            --override-arch=amd64 \
            --override-os=linux \
            docker://docker.io/mysql:8.4.4 \
            docker://crpi-xgj9z1app199hujj.cn-shanghai.personal.cr.aliyuncs.com/wsk_services/mysql:8.4.4 \
            --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}

          # 私有镜像需添加 --src-creds
          # skopeo copy \
          #   --src-creds=${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} \
          #   docker://docker.io/private-repo/image:tag \
          #   docker://your-personal-registry... \
          #   --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
